[package]
name = "taproot-inheritance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk = "0.19.0"
bitcoin = "0.28.1"
env_logger = "0.6.1"
miniscript = "7.0.0"
secp256k1 = "0.22.1"